default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: starter_development_database

test:
  <<: *default
  database: starter_test_database

production:
  <<: *default
  database: starter_production_database
